name: Update Docker Hub Description from Readme
on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: floholz/goclean
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true